// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtWdrfml91qyKOn1b7rxiBuTm-EMjCyk',
    appId: '1:955499126701:web:2fd2359abc9bcf47ff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    authDomain: 'facebook-clone-9f92c.firebaseapp.com',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
    measurementId: 'G-KGR63WMR29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_VDMcxzmjK-ZU_DCX2jowGW9u_TApVc',
    appId: '1:955499126701:android:61ce9ba02a7d501dff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2DLRtmYBcYfOFxxPZXOBl2stF6_NVthM',
    appId: '1:955499126701:ios:1e27040b3c890c98ff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
    androidClientId: '955499126701-vj9qdf0lc2inr76j5qll7qognesr0q73.apps.googleusercontent.com',
    iosClientId: '955499126701-8kvgtcmo3pamqt1up435bvck06bkrpfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinancialManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2DLRtmYBcYfOFxxPZXOBl2stF6_NVthM',
    appId: '1:955499126701:ios:1e27040b3c890c98ff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
    androidClientId: '955499126701-vj9qdf0lc2inr76j5qll7qognesr0q73.apps.googleusercontent.com',
    iosClientId: '955499126701-8kvgtcmo3pamqt1up435bvck06bkrpfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinancialManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrtWdrfml91qyKOn1b7rxiBuTm-EMjCyk',
    appId: '1:955499126701:web:e814d33bf63269ceff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    authDomain: 'facebook-clone-9f92c.firebaseapp.com',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
    measurementId: 'G-GSN6H100ZD',
  );
}
