// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcA4kyXhUvt-VSpAW4K9jJlojT3DBl5XQ',
    appId: '1:423333058295:web:d9fb74ffcd20eb0cc825f2',
    messagingSenderId: '423333058295',
    projectId: 'luxfinance-93617',
    authDomain: 'luxfinance-93617.firebaseapp.com',
    storageBucket: 'luxfinance-93617.appspot.com',
    measurementId: 'G-1Z8BZ02KXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeXPo4CTj_w0yDqqYlcrwxOtco5YFZLG0',
    appId: '1:423333058295:android:6ff7f440da92ad4dc825f2',
    messagingSenderId: '423333058295',
    projectId: 'luxfinance-93617',
    storageBucket: 'luxfinance-93617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cP2OGaYZP96Dpxb9RjJz48Jq0xVHfEk',
    appId: '1:423333058295:ios:fccf846ecdbaafb3c825f2',
    messagingSenderId: '423333058295',
    projectId: 'luxfinance-93617',
    storageBucket: 'luxfinance-93617.appspot.com',
    iosBundleId: 'com.example.personalFinancialManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3cP2OGaYZP96Dpxb9RjJz48Jq0xVHfEk',
    appId: '1:423333058295:ios:fccf846ecdbaafb3c825f2',
    messagingSenderId: '423333058295',
    projectId: 'luxfinance-93617',
    storageBucket: 'luxfinance-93617.appspot.com',
    iosBundleId: 'com.example.personalFinancialManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcA4kyXhUvt-VSpAW4K9jJlojT3DBl5XQ',
    appId: '1:423333058295:web:2af5a1b078119b4bc825f2',
    messagingSenderId: '423333058295',
    projectId: 'luxfinance-93617',
    authDomain: 'luxfinance-93617.firebaseapp.com',
    storageBucket: 'luxfinance-93617.appspot.com',
    measurementId: 'G-TWW3P7V1NN',
  );

}